---
- name: 'Include {{ ansible_os_family }}.yml'
  include_vars: '{{ ansible_os_family }}.yml'

- name: 'Install apt packages'
  apt:
    name: '{{ item }}'
    state: 'present'
  with_items: '{{ apt_packages }}'
  when: 'ansible_os_family == "Debian"'
